<?php

/**
 * Contao Open Source CMS
 * Copyright (C) 2005-2011 Leo Feyer
 *
 * Formerly known as TYPOlight Open Source CMS.
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program. If not, please visit the Free
 * Software Foundation website at <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 * @copyright  MEN AT WORK 2012
 * @package    geoprotection
 * @license    GNU/LGPL
 * @filesource
 */
 
$countriesByContinent = array
(
	'antarctica' => array(
		'aq' => 'Antarctica',
		'bv' => 'Bouvet Island',
		'tf' => 'French Southern Territories'
	
	),
	'australia' => array(
		'as' => 'American Samoa',
		'au' => 'Australia',
		'ck' => 'Cook Islands',
		'fj' => 'Fiji',
		'fm' => 'Micronesia',
		'hm' => 'Heard and McDonald Islands',		
		'ki' => 'Kiribati',		
		'mh' => 'Marshall Islands',
		'mp' => 'Northern Mariana Islands',		
		'nc' => 'New Caledonia',	
		'nf' => 'Norfolk Island',	
		'nr' => 'Nauru',
		'nu' => 'Niue',
		'nz' => 'New Zealand',		
		'pf' => 'French Polynesia',		
		'pg' => 'Papua New Guinea',	
		'pn' => 'Pitcairn Island',
		'pw' => 'Palau',	
		'sb' => 'Solomon Islands',
		'tk' => 'Tokelau',
		'tl' => 'Timor-Leste',	
		'to' => 'Tonga',	
		'tv' => 'Tuvalu',	
		'vu' => 'Vanuatu',	
		'wf' => 'Wallis and Futuna Islands',
		'ws' => 'Samoa',
	
	),	
	'africa' => array(
		'ao' => 'Angola',
		'bf' => 'Burkina Faso',
		'bi' => 'Burundi',
		'bj' => 'Benin',
		'bw' => 'Botswana',
		'cd' => 'Congo, The Democratic Republic of the',
		'cf' => 'Central African Republic',
		'cg' => 'Congo, Republic of',
		'ci' => 'Cote d\'Ivoire',
		'cm' => 'Cameroon',
		'cv' => 'Cape Verde',
		'dj' => 'Djibouti',	
		'dz' => 'Algeria',		
		'eg' => 'Egypt',
		'eh' => 'Western Sahara',
		'er' => 'Eritrea',
		'et' => 'Ethiopia',
		'fk' => 'Falkland Islands (Malvinas)',
		'ga' => 'Gabon',
		'gh' => 'Ghana',
		'gi' => 'Gibraltar',	
		'gm' => 'Gambia',
		'gn' => 'Guinea',
		'gq' => 'Equatorial Guinea',	
		'gw' => 'Guinea-Bissau',
		'ke' => 'Kenya',
		'km' => 'Comoros',
		'lr' => 'Liberia',
		'ls' => 'Lesotho',		
		'ly' => 'Libyan Arab Jamahiriya',
		'ma' => 'Morocco',	
		'mg' => 'Madagascar',
		'ml' => 'Mali',
		'mr' => 'Mauritania',
		'mu' => 'Mauritius',		
		'mw' => 'Malawi',
		'mz' => 'Mozambique',
		'na' => 'Namibia',
		'ne' => 'Niger',
		'ng' => 'Nigeria',	
		're' => 'Reunion Island',	
		'rw' => 'Rwanda',
		'sc' => 'Seychelles',
		'sd' => 'Sudan',
		'sh' => 'Saint Helena',
		'sl' => 'Sierra Leone',
		'sn' => 'Senegal',
		'so' => 'Somalia',
		'st' => 'Sao Tome and Principe',
		'sz' => 'Swaziland',
		'td' => 'Chad',
		'tg' => 'Togo',
		'tn' => 'Tunisia',
		'tz' => 'Tanzania',
		'ug' => 'Uganda',
		'yt' => 'Mayotte',
		'za' => 'South Africa',
		'zm' => 'Zambia',
		'zw' => 'Zimbabwe',

	),
	'north america' => array(
		'ag' => 'Antigua and Barbuda',
		'ai' => 'Anguilla',
		'an' => 'Netherlands Antilles',	
		'aw' => 'Aruba',
		'bb' => 'Barbados',
		'bm' => 'Bermuda',
		'bs' => 'Bahamas',
		'bz' => 'Belize',
		'ca' => 'Canada',
		'cr' => 'Costa Rica',
		'cu' => 'Cuba',
		'dm' => 'Dominica',
		'gd' => 'Grenada',
		'gl' => 'Greenland',
		'gp' => 'Guadeloupe',
		'gt' => 'Guatemala',
		'hn' => 'Honduras',
		'ht' => 'Haiti',
		'jm' => 'Jamaica',
		'kn' => 'Saint Kitts and Nevis',
		'ky' => 'Cayman Islands',
		'mf' => 'Saint Martin',
		'mq' => 'Martinique',
		'ms' => 'Montserrat',
		'mx' => 'Mexico',
		'ni' => 'Nicaragua',
		'pm' => 'Saint Pierre and Miquelon',
		'pr' => 'Puerto Rico',
		'sv' => 'El Salvador',
		'tc' => 'Turks and Caicos Islands',
		'us' => 'United States',
		'vg' => 'Virgin Islands, British',
		
		
		
	
	),
	'south america' => array(
		'ar' => 'Argentina',
		'bo' => 'Bolivia',
		'br' => 'Brazil',
		'cl' => 'Chile',
		'co' => 'Colombia',
		'do' => 'Dominican Republic',
		'ec' => 'Ecuador',
		'gf' => 'French Guiana',
		'gs' => 'South Georgia and the South Sandwich Islands',
		'gy' => 'Guyana',
		'lc' => 'Saint Lucia',
		'pa' => 'Panama',
		'pe' => 'Peru',
		'py' => 'Paraguay',
		'sr' => 'Suriname',
		'tt' => 'Trinidad and Tobago',
		'uy' => 'Uruguay',
		'vc' => 'Saint Vincent and the Grenadines',
		've' => 'Venezuela',
		'vi' => 'Virgin Islands, U.S.',
		
		
	),
	'europe' => array(
		'ad' => 'Andorra',
		'al' => 'Albania',
		'at' => 'Austria',
		'ax' => 'Aland Islands',
		'ba' => 'Bosnia and Herzegovina',
		'be' => 'Belgium',
		'bg' => 'Bulgaria',
		'by' => 'Belarus',
		'ch' => 'Switzerland',
		'cz' => 'Czech Republic',
		'de' => 'Germany',
		'dk' => 'Denmark',
		'ee' => 'Estonia',
		'es' => 'Spain',
		'fi' => 'Finland',
		'fo' => 'Faroe Islands',
		'fr' => 'France',
		'gb' => 'United Kingdom',
		'ge' => 'Georgia',
		'gg' => 'Guernsey',
		'gr' => 'Greece',
		'hr' => 'Croatia/Hrvatska',
		'hu' => 'Hungary',
		'ie' => 'Ireland',
		'im' => 'Isle of Man',
		'is' => 'Iceland',
		'it' => 'Italy',
		'je' => 'Jersey',
		'li' => 'Liechtenstein',
		'lt' => 'Lithuania',
		'lu' => 'Luxembourg',
		'lv' => 'Latvia',
		'mc' => 'Monaco',
		'md' => 'Moldova, Republic of',
		'me' => 'Montenegro',
		'mk' => 'Macedonia',
		'mt' => 'Malta',
		'nl' => 'Netherlands',
		'no' => 'Norway',
		'pl' => 'Poland',
		'pt' => 'Portugal',
		'ro' => 'Romania',
		'rs' => 'Serbia',
		'se' => 'Sweden',
		'si' => 'Slovenia',
		'sj' => 'Svalbard and Jan Mayen Islands',
		'sk' => 'Slovak Republic',
		'sm' => 'San Marino',
		'ua' => 'Ukraine',
		'va' => 'Holy See (Vatican City State)',
	
	),	
	'asia' => array(
		'ae' => 'United Arab Emirates',
		'af' => 'Afghanistan',
		'am' => 'Armenia',	
		'az' => 'Azerbaijan',
		'bd' => 'Bangladesh',
		'bh' => 'Bahrain',
		'bl' => 'Saint Barthélemy',
		'bn' => 'Brunei Darussalam',
		'bt' => 'Bhutan',
		'cc' => 'Cocos (Keeling) Islands',
		'cn' => 'China',
		'cx' => 'Christmas Island',
		'cy' => 'Cyprus',
		'gu' => 'Guam',
		'hk' => 'Hong Kong',
		'id' => 'Indonesia',
		'il' => 'Israel',
		'in' => 'India',
		'io' => 'British Indian Ocean Territory',
		'iq' => 'Iraq',
		'ir' => 'Iran',
		'jo' => 'Jordan',
		'jp' => 'Japan',
		'kg' => 'Kyrgyzstan',
		'kh' => 'Cambodia',
		'kp' => 'North Korea',
		'kr' => 'South Korea',
		'kw' => 'Kuwait',
		'kz' => 'Kazakhstan',
		'la' => 'Lao',
		'lb' => 'Lebanon',
		'lk' => 'Sri Lanka',	
		'mm' => 'Myanmar',
		'mn' => 'Mongolia',
		'mo' => 'Macau',
		'mv' => 'Maldives',
		'my' => 'Malaysia',
		'np' => 'Nepal',
		'om' => 'Oman',
		'ph' => 'Philippines',
		'pk' => 'Pakistan',
		'ps' => 'Palestinian Territories',
		'qa' => 'Qatar',
		'ru' => 'Russian Federation',
		'sa' => 'Saudi Arabia',
		'sg' => 'Singapore',
		'sy' => 'Syrian Arab Republic',
		'th' => 'Thailand',
		'tj' => 'Tajikistan',
		'tm' => 'Turkmenistan',
		'tr' => 'Turkey',
		'tw' => 'Taiwan',
		'um' => 'United States Minor Outlying Islands',
		'uz' => 'Uzbekistan',
		'vn' => 'Vietnam',
		'ye' => 'Yemen',
	)
);